export enum ActionTypes {
    GET_POKEMON_LIST_SUCCESS = 'GET_POKEMON_LIST_SUCCESS',
    GET_POKEMON_LIST_FAILURE = 'GET_POKEMON_LIST_FAILURE',

    GET_POKEMON_DETAIL_SUCCESS = 'GET_POKEMON_DETAIL_SUCCESS',
    GET_POKEMON_DETAIL_FAILURE = 'GET_POKEMON_DETAIL_FAILURE',

    CLEAR_POKEMON_DETAILS = 'CLEAR_POKEMON_DETAILS',
}